### ISSUE TITLE
How to prepare pretrain data for LF-VILA?

### ISSUE THREAD

**Issue by yliu-cs** [microsoft/XPretrain#18]
What is the data format in `datasets/hdvila100m/video_clip_3fps`, `datasets/lfvila_data/pretrain/train_db` and `datasets/lfvila_data/pretrain/val.jsonl` mentioned in `src/configs/pretrain_stage1.yaml` ?
Can you provide specific reference examples or processes (for long-form video and annotations respectively) ?

**Comment by ycsun1972** [comment]
Hi, thank you for your interest in our work.
(1) Our videos are a subset of hdvila100m, please refer to the instruction of [hdvila100m](https://github.com/microsoft/XPretrain/tree/main/hd-vila-100m) and download the original videos and cut them into clips. In order to reduce the data reading overhead, we have compressed the raw video clips to 3fps.
(2) For datasets/lfvila_data/pretrain/train_db and datasets/lfvila_data/pretrain/val.jsonl, it consists of lists of [clip_id, text] pairs built from the metadata of hdvila100m.  We combine pairs that are contiguous in time to form long videos. We provide the clipids of [LF-VILA-8M](https://hdvila.blob.core.windows.net/dataset/lfvila8m_clipid.zip?sp=r&st=2023-04-25T08:23:12Z&se=2026-04-06T16:23:12Z&spr=https&sv=2021-12-02&sr=b&sig=nD2o554duJWboPVVC3wVgro2pDVjOySl2TORi%2B2YLKM%3D), the text can be found in the metadata of hdvila100m.

**Comment by bei21** [comment]
Also, please refer to #7 for transcripts of HD-VILA-100M.
